// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgZHgS1OQgJtpI4ye9ODUIdsn5MYL5Fgs',
    appId: '1:358691304491:web:6a9a145b5c7a4417e7266e',
    messagingSenderId: '358691304491',
    projectId: 'routiner-7559a',
    authDomain: 'routiner-7559a.firebaseapp.com',
    storageBucket: 'routiner-7559a.firebasestorage.app',
    measurementId: 'G-PXGH8Q6BYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRg_fYa5mlfy20AYeavw0RYx0IawRLPYY',
    appId: '1:358691304491:android:8208d8daa18dd9cbe7266e',
    messagingSenderId: '358691304491',
    projectId: 'routiner-7559a',
    storageBucket: 'routiner-7559a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB9swxnLTZ4et9dV2s2Y_Mqa74AOyOFpE',
    appId: '1:358691304491:ios:cc9ae99a357a5734e7266e',
    messagingSenderId: '358691304491',
    projectId: 'routiner-7559a',
    storageBucket: 'routiner-7559a.firebasestorage.app',
    iosClientId: '358691304491-71tkvfql3roq1d9pcv5dl0626bmtltv4.apps.googleusercontent.com',
    iosBundleId: 'com.example.routiner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB9swxnLTZ4et9dV2s2Y_Mqa74AOyOFpE',
    appId: '1:358691304491:ios:cc9ae99a357a5734e7266e',
    messagingSenderId: '358691304491',
    projectId: 'routiner-7559a',
    storageBucket: 'routiner-7559a.firebasestorage.app',
    iosClientId: '358691304491-71tkvfql3roq1d9pcv5dl0626bmtltv4.apps.googleusercontent.com',
    iosBundleId: 'com.example.routiner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgZHgS1OQgJtpI4ye9ODUIdsn5MYL5Fgs',
    appId: '1:358691304491:web:7e99db18125ddf01e7266e',
    messagingSenderId: '358691304491',
    projectId: 'routiner-7559a',
    authDomain: 'routiner-7559a.firebaseapp.com',
    storageBucket: 'routiner-7559a.firebasestorage.app',
    measurementId: 'G-QFQHR7JS5R',
  );
}
